# Generated by Django 3.2.9 on 2021-11-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=100)),
                ('compenyname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('clientcity', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equepmentdetails2',
            fields=[
                ('equepmentid', models.AutoField(primary_key=True, serialize=False)),
                ('equepmentname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('roleid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseid', models.AutoField(primary_key=True, serialize=False)),
                ('warehousename', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('werehousecity', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.role')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projecttitle', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('projectcity', models.CharField(max_length=100)),
                ('contecnumber', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.client')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.project')),
            ],
        ),
        migrations.CreateModel(
            name='EquepmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equepmentSerialNumbeer', models.CharField(max_length=50)),
                ('equepmentname', models.CharField(max_length=50, null=True)),
                ('equepmentcity', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=200)),
                ('dimension', models.CharField(max_length=50)),
                ('equepmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.equepmentdetails2')),
                ('plantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.plant')),
            ],
        ),
    ]
