# Generated by Django 3.2.9 on 2021-11-18 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equepmentmaster',
            name='equepmentname',
        ),
        migrations.AddField(
            model_name='equepmentmaster',
            name='warehouseid',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='moduls.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equepmentmaster',
            name='equepmentSerialNumbeer',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='projectid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduls.project'),
        ),
    ]
