# Generated by Django 3.2.9 on 2021-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0003_alter_equepmentmaster_plantid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equepmentmaster',
            name='equepmentcity',
            field=models.CharField(default='in ware house', max_length=100),
        ),
    ]
