# Generated by Django 3.2.9 on 2021-11-19 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0004_auto_20211118_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clientid',
        ),
        migrations.AddField(
            model_name='client',
            name='clientcountry',
            field=models.CharField(max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='projectcountry',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='clientcity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='compenyname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectcity',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.AutoField(primary_key=True, serialize=False)),
                ('disp_siteid', models.CharField(max_length=20)),
                ('sitecountry', models.CharField(max_length=50)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.client')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.site'),
            preserve_default=False,
        ),
    ]
