# Generated by Django 3.2.9 on 2021-11-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0005_auto_20211119_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='disp_siteid',
        ),
    ]
