# Generated by Django 3.2.9 on 2021-11-19 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0006_remove_site_disp_siteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
