# Generated by Django 3.2.9 on 2021-11-24 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0008_site_sitecity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equepmentmaster',
            name='plantid',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='siteid',
        ),
        migrations.AddField(
            model_name='equepmentmaster',
            name='projectid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduls.project'),
        ),
        migrations.AddField(
            model_name='plant',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='plantid',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='moduls.plant'),
            preserve_default=False,
        ),
    ]
