# Generated by Django 3.2.9 on 2021-11-24 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0009_auto_20211124_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equepmentmaster',
            name='equepmentcity',
        ),
        migrations.RemoveField(
            model_name='equepmentmaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equepmentmaster',
            name='projectid',
        ),
        migrations.AddField(
            model_name='equepmentmaster',
            name='subequipmentid',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Assignedequipment',
            fields=[
                ('assignid', models.AutoField(primary_key=True, serialize=False)),
                ('projectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduls.project')),
                ('subequipmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduls.equepmentmaster')),
            ],
        ),
    ]
