# Generated by Django 3.2.9 on 2021-11-24 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduls', '0010_auto_20211124_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedequipment',
            name='subequipmentid',
        ),
        migrations.AddField(
            model_name='assignedequipment',
            name='subequipmentsr',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
